name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag zigoprofesia/luft:prod --target prod
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag zigoprofesia/luft:test --target test
    - name: Login DockerHub
      run: docker login --username=${{ secrets.DOCKERHUB_USERNAME }} --password=${{ secrets.DOCKERHUB_TOKEN }}
    - name: Docker push
      run: docker push zigoprofesia/luft:prod
    - name: Docker push
      run: docker push zigoprofesia/luft:test
